FROM ubuntu:22.04 as base

# install curl, wget, and other tools
RUN apt-get update \
    && apt-get install -y \
    curl \
    wget \
    apt-transport-https 
    #lsb-release \
    #gnupg

RUN apt-get install -y openjdk-21-jre-headless && apt-get update


# check for arguments
ARG IMAGE_NAME
RUN echo "image name is --> "${IMAGE_NAME}

LABEL "type"="${IMAGE_NAME}"
LABEL "nadeem"="khalid"