name: dotnet 8 - ubuntu 22

on:
  push:
    branches:
      - main
env:
  message: "This is a test message"

  ART_REGISTORY: "apli.jfrog.io"
  ART_REPO: "local-docker"
  ART_FOLDER: "dotnet8-ubuntu22"
  JF_USER: "nk1752@outlook.com"

  BASE_IMAGE_TAG: "v2.0.0"
  BASE_IMAGE_NAME: "dotnet8-base-image"

  IMAGE_SDK: "dotnet8-sdk"
  IMAGE_SDK_TAG: "v1.0.0"

  PROJECT_NAME: "dotnet8-ubuntu22"

jobs:
  build-push-base-images:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write
      packages: write
      id-token: write

    steps:
      - name: checkout
        uses: actions/checkout@v4

        # build docker image from Dockerfile
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker login to Jfrog
        uses: docker/login-action@v2
        with:
          username: ${{ env.JF_USER }}
          password: ${{ secrets.JF_DOCKER_ACCESS_TOKEN }}
          registry: ${{ env.ART_REGISTORY }}

      - name: build docker sdk image
        run: |
          docker build -f ./dockerfiles/Dockerfile.dotnet8-ubuntu22 \
                -t ${{env.IMAGE_SDK}} \
                --build-arg IMAGE_NAME="${{env.IMAGE_SDK}}" .
          docker images
          docker tag ${{ env.IMAGE_SDK}} ${{env.ART_REGISTORY}}/${{env.ART_REPO}}/${{ env.IMAGE_SDK}}:${{ env.IMAGE_SDK_TAG}}
          docker push ${{env.ART_REGISTORY}}/${{env.ART_REPO}}/${{ env.IMAGE_SDK}}:${{ env.IMAGE_SDK_TAG}}
