name: dotnet8 -> ubuntu22

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  ART_REGISTORY: "appli.jfrog.io"
  ART_REPO: "local-docker/alm"
  JF_USER: "nk1752@outlook.com"

jobs:
  ubuntu-base-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write
      packages: write
      id-token: write

    steps:
      
      - name: checkout
        uses: actions/checkout@v4.1.6

        # build docker image from Dockerfile
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.4.0

      - name: Docker login to Jfrog
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ env.JF_USER }}
          password: ${{ secrets.JF_DOCKER_ACCESS_TOKEN }}
          registry: ${{ env.ART_REGISTORY }}
        
        # ************ metadata ************
      - name: metadata
        id: metadata
        uses: docker/metadata-action@v5.0.0
        with:
          images: ${{ env.ART_REGISTORY }}/${{ env.ART_REPO }}/base-images/ubuntu:22.04
          tags: |
            ${{ env.IMAGE }}:22.04
            ${{ env.IMAGE }}:latest
        env:
          IMAGE: ${{ env.ART_REGISTORY }}/${{ env.ART_REPO }}/base-images/ubuntu

      - name: echo
        run: echo ${{ steps.metadata.outputs.tags }}

        # ************ base image ************
      - name: build dotnet8 base image
        uses: docker/build-push-action@v6.3.0
        with:
          context: .
          file: ./dockerfiles/Dockerfile.ubuntu22
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: |
            OpenShift=ubuntu22
            "ALM=dotnet8-sdk"
        env:
          IMAGE: ${{ env.ART_REGISTORY }}/${{ env.ART_REPO }}/base-images/ubuntu

      
            
         
      
  # ************ dotnet8 images job ************
  dotnet8-base-images:
    runs-on: ubuntu-latest
    needs: ubuntu-base-image

    permissions:
      contents: read
      pull-requests: write
      packages: write
      id-token: write

    steps:
      - name: checkout
        uses: actions/checkout@v4.1.6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.4.0

      - name: Docker login to Jfrog
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ env.JF_USER }}
          password: ${{ secrets.JF_DOCKER_ACCESS_TOKEN }}
          registry: ${{ env.ART_REGISTORY }}
      
        # ************ sdk image ************
      - name: build dotnet8 sdk image
        uses: docker/build-push-action@v6.3.0
        with:
          context: .
          file: ./dockerfiles/Dockerfile.dotnet8-sdk
          push: true
          tags: |
            ${{ env.IMAGE }}:8
            ${{ env.IMAGE }}:dotnet8-sdk
          labels: |
            "OpehShift=ubuntu22"
            ALM="dotnet8-sdk"
        env:
          IMAGE: ${{ env.ART_REGISTORY }}/${{ env.ART_REPO }}/dotnet/8-sdk
          
        # ************ runtime image ************
      - name: build dotnet8 runtime image
        uses: docker/build-push-action@v6.3.0
        with:
          context: .
          file: ./dockerfiles/Dockerfile.dotnet8-runtime
          push: true
          tags: |
            ${{ env.IMAGE }}:8-runtime
            ${{ env.IMAGE }}:dotnet8-runtime
        env:
          IMAGE: ${{ env.ART_REGISTORY }}/${{ env.ART_REPO }}/dotnet/8-runtime

        # ************ aspnet image ************
      - name: build dotnet8 aspnet image
        uses: docker/build-push-action@v6.3.0
        with:
          context: .
          file: ./dockerfiles/Dockerfile.dotnet8-aspnet
          push: true
          tags: |
            ${{ env.IMAGE }}:8-aspnet
            ${{ env.IMAGE }}:dotnet8-aspnet
        env:
          IMAGE: ${{ env.ART_REGISTORY }}/${{ env.ART_REPO }}/dotnet/8-aspnet
          
