name: java 21 - ubuntu 22

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      publish:
        description: "push to artifactory"
        required: true
        default: "false"
        type: choice
        options:
          - "true"
          - "false"
env:
  message: "This is a test message"

  ART_REGISTORY: "rgnadeem.jfrog.io"
  ART_REPO: "local-docker"
  ART_FOLDER: "java21-ubuntu22"
  JF_USER: "nadeem.khalid@regions.com"

  IMAGE_21: "java-21"
  IMAGE_21_TAG: "v2.1.0"

  PROJECT_NAME: "java21-ubuntu22"

jobs:
  build-push-base-images:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write
      packages: write
      id-token: write

    steps:
      - name: checkout
        uses: actions/checkout@v4

        # build docker image from Dockerfile
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker login to Jfrog
        uses: docker/login-action@v2
        with:
          username: ${{ env.JF_USER }}
          password: ${{ secrets.JF_DOCKER_ACCESS_TOKEN }}
          registry: ${{ env.ART_REGISTORY }}

      - name: build docker sdk image
        run: |
          docker build -f ./${{env.PROJECT_NAME}}/Dockerfile \
                -t ${{env.IMAGE_21}} \
                --build-arg IMAGE_NAME="${{env.IMAGE_21}}" .
          docker images
          docker tag ${{ env.IMAGE_21}} ${{env.ART_REGISTORY}}/${{env.ART_REPO}}/${{ env.IMAGE_21}}:${{ env.IMAGE_21_TAG}}
          docker push ${{env.ART_REGISTORY}}/${{env.ART_REPO}}/${{ env.IMAGE_21}}:${{ env.IMAGE_21_TAG}}
