name: play

on:
  schedule:
    - cron: "*/20 */1 * * *" # At every 15th minute past every hour on every day-of-month.

env:
  ART_REGISTORY: "rgnadeem.jfrog.io"
  PROJECT_NAME: "python312-ubuntu22"
  JF_USER: "nadeem.khalid@regions.com"

  WORKFLOW_MSG: "This is a workflow message"

jobs:
  echo:
    runs-on: ubuntu-latest

    env:
      JOB_MSG: "This is a job message"

    permissions:
      contents: read
      pull-requests: write
      packages: write
      id-token: write

    steps:
      - name: env
        
        run: |

          # display github context
          echo "GITHUB_REPOSITORY --> ${{ github.repository }}"
          echo "GITHUB_REPOSITORY_OWNER --> ${{ github.repository_owner }}"
          echo "GITHUB_RUN_ID --> ${{ github.run_id }}"
          echo "GITHUB_RUN_NUMBER --> ${{ github.run_number }}"
          echo "GITHUB_ACTOR --> ${{ github.actor }}"
          echo "GITHUB_WORKFLOW --> ${{ github.workflow }}"
          echo "GITHUB_HEAD_REF --> ${{ github.head_ref }}"
          echo "GITHUB_BASE_REF --> ${{ github.base_ref }}"
          echo "GITHUB_EVENT_NAME --> ${{ github.event_name }}"
          echo "GITHUB_EVENT_PATH --> ${{ github.event_path }}"
          echo "GITHUB_WORKSPACE --> ${{ github.workspace }}"
          echo "GITHUB_SHA --> ${{ github.sha }}"
          echo "GITHUB_REF (branch name) --> ${{ github.ref }}"
          echo "GITHUB_TRIGGER_ACTOR --> ${{ github.triggering_actor }}"

          # display branch name
          echo "BRANCH_NAME --> ${{ github.ref }}"

      - name: build vars
        run: |
          echo "BUILD_NUMBER=$BUILD_RUN_NUMBER" >> $GITHUB_ENV
          echo "GITHUB_BRANCH=${GITHUB_REF#refs/heads/}" > $GITHUB_ENV

      - name: display vars
        run: |
          echo "GITHUB_BRANCH=${{ env.GITHUB_BRANCH }}"
          echo "BUILD_NUMBER=${{ env.BUILD_NUMBER }}"
          msg="This is a message"
          echo "msg=$msg" >> $GITHUB_ENV
          echo "WORKFLOW_MSG=${{ env.msg }}"
          
    